# Collecting base data from ifc files

In [5]:
# imports
from pathlib import Path
import pandas as pd
import sys

# helpers
sys.path.insert(0, "../../")
from dataloader import extract_ifc_main_properties

In [6]:
# data directory and output path
IFC_MODELS_DIR = "../../0_data/1_ifc_models"
OUTPUT_PATH = "ifc_data.parquet"

In [7]:
# get locations of ifc files
ifc_files = sorted(Path(IFC_MODELS_DIR).rglob("*.ifc"), reverse=True)

# print count and example
print("Count of IFC-Files: ", len(ifc_files))
ifc_files[0]

Count of IFC-Files:  35

PosixPath('../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_.ifc')

In [8]:
# process each ifc file and save data to .parquet
all_records = []
for ifc_path in ifc_files:
    print(f"  Processing: {ifc_path.name}")
    all_records.extend(extract_ifc_main_properties(ifc_path))

df = pd.DataFrame(all_records)
df

  Processing: ZUST_P_ARC_VOL_.ifc
  Processing: ZUST_P_ARC_EBK_.ifc
  Processing: ZUST_C_ARC_VOL_.ifc
  Processing: ZUST_C_ARC_NGF_.ifc
  Processing: ZUST_C_ARC_EBK_.ifc
  Processing: ZUST_B_ARC_VOL_.ifc
  Processing: ZUST_B_ARC_NGF_.ifc
  Processing: ZUST_B_ARC_EBK_.ifc
  Processing: ZUST_A_ARC_VOL_.ifc
  Processing: ZUST_A_ARC_NGF_.ifc
  Processing: ZUST_A_ARC_EBK_.ifc
  Processing: ZUST_ARC_NGF_.ifc
  Processing: ZEGA_52_ARC_eBKPh_260127.ifc
  Processing: RALU_32_ARC_eBKPh.ifc
  Processing: LUMU_31_ARC_eBKPh_V3.ifc
  Processing: KEPR_31_ARC_eBKPh_260209.ifc
  Processing: KEHO_31_ARC_eBKPh_260127.ifc
  Processing: IMBU_52_ARC_eBKPh_260127.ifc
  Processing: GSRH_31_ARC_eBKPh_V2.ifc
  Processing: GSRH_31_ARC_eBKPh_V1.ifc
  Processing: GERB_31_ARC_eBKPh_250221.ifc
  Processing: GERB_31_ARC_eBKPh_241209.ifc
  Processing: ESAK_21_ARC_eBKPh.ifc
  Processing: CHLI_51_AVM_Haus B.ifc
  Processing: CHLI_51_AVM_Haus A.ifc
  Processing: CHLI_51_ANG_Haus B.ifc
  Processing: CHLI_51_ANG_Haus A.ifc
  Processing: CHLI_51_ALE_Haus B_eBKP-H.ifc
  Processing: CHLI_51_ALE_Haus A_eBKP-H.ifc
  Processing: BRUT_41_ARC_Haus C_eBKPh.ifc
  Processing: BRUT_41_ARC_Haus B_eBKPh.ifc
  Processing: BRUT_41_ARC_Haus A_eBKPh.ifc
  Processing: ADEM_41_ARC_eBKPh_260202.ifc
  Processing: ADEM_41_ARC_eBKPh_250701.ifc
  Processing: ADEM_41_ARC_eBKPh_250406.ifc

,file_path,model_name,ifc_schema,guid,ifc_entity,predefined_type
0,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1mvS9idiD3wBSng3jTXYT_,IfcBuildingElementProxy,NOTDEFINED
1,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1i$ZkNLnT42OfhsY2HRYEB,IfcBuildingElementProxy,NOTDEFINED
2,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,04t05b7LbESvNTIP4YWVjz,IfcBuildingElementProxy,NOTDEFINED
3,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,00tMo7QcxqWdIGvc4sMN2A,IfcBuilding,NaN
4,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,3eYt9TfVT42ezAX4OpSOsQ,IfcBuildingStorey,NaN
...,...,...,...,...,...,...
127422,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,3WjCdiWjDBQgNMTPRooJMm,IfcSpace,INTERNAL
127423,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,30dJ7acrD23hi5l7wHY2qF,IfcSpace,INTERNAL
127424,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,1ApVC9mAn3jeKfhThRu9oz,IfcSpace,GFA
127425,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,3ypBL9h79BveiYOzmNg8c7,IfcSpace,INTERNAL
127426,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406,IFC4,0hNnaYzjHFTRJHO6j9rugt,IfcSpace,INTERNAL

In [9]:
# save ifc base data
df.to_parquet(OUTPUT_PATH, index=False)

print(f"\nSaved {len(df):,} rows to: {OUTPUT_PATH}\n")

Saved 127,427 rows to: ifc_data.parquet

In [10]:
df.columns

Index(['file_path', 'model_name', 'ifc_schema', 'guid', 'ifc_entity',
       'predefined_type'],
      dtype='str')

In [11]:
# first data insight of columns
df.head(10)

,file_path,model_name,ifc_schema,guid,ifc_entity,predefined_type
0,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1mvS9idiD3wBSng3jTXYT_,IfcBuildingElementProxy,NOTDEFINED
1,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1i$ZkNLnT42OfhsY2HRYEB,IfcBuildingElementProxy,NOTDEFINED
2,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,04t05b7LbESvNTIP4YWVjz,IfcBuildingElementProxy,NOTDEFINED
3,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,00tMo7QcxqWdIGvc4sMN2A,IfcBuilding,NaN
4,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,3eYt9TfVT42ezAX4OpSOsQ,IfcBuildingStorey,NaN
5,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,3svIgCMrX8j8Gpr2WkHfaW,IfcBuildingStorey,NaN
6,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,33I9o0UEnuS63A86ORkJnZ,IfcSite,NaN
7,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,1HyWKnRVf2nQPdSu_qBpKS,IfcSpace,GFA
8,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,330umOG8j8lh$KH3zRhUgt,IfcSpace,GFA
9,../../0_data/1_ifc_models/ZUST/ZUST_P_ARC_VOL_...,ZUST_P_ARC_VOL_,IFC4,0RuGd4rvD2xeZxAp7YWBVl,IfcSpace,GFA

In [12]:
# show different entitties
len(df["ifc_entity"].value_counts()), len(df["predefined_type"].value_counts())

(43, 79)

In [13]:
# see all guid's, should be unique
df["guid"].value_counts()

guid
00tMo7QcxqWdIGvc4sMN2A    35
3eYt9TfVT42ezAX4OpSOsQ    35
3svIgCMrX8j8Gpr2WkHfaW    35
3NscPmsxv7yOs3PvwPDAMH    29
2FcQ$VfcDClOrgjBNOA$cL    28
                          ..
1l9DLinKn3ygxxzj2uec_3     1
0nwohU1qf14Rm3V5HUDWeH     1
0e1EVFOyD26g9Z7qHNhG4S     1
3s82zmlxP4CRb7E$9YJbAM     1
2ss19PS$j60gcp9Pl39gDO     1
Name: count, Length: 108457, dtype: int64

In [14]:
# show all dupliacate elements
counts = df["guid"].value_counts()
len(counts[counts > 1])

14147