# Collecting label data from excel files

In [1]:
# imports
from pathlib import Path
import pandas as pd
import sys

# helpers
sys.path.insert(0, "../../")
from dataloader import extract_excel_label_informations

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [2]:
# data directory and output path
EXCEL_MODELS_DIR = "../../0_data/1_ifc_models"
OUTPUT_PATH = "label_data.parquet"

In [3]:
# get locations of ifc files
xlsx_files = sorted(Path(EXCEL_MODELS_DIR).rglob("*.xlsx"), reverse=True)

# print count and example
print("Count of Excel-Files: ", len(xlsx_files))
xlsx_files[0]

Count of Excel-Files:  37

PosixPath('../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_Alle_labels.xlsx')

In [4]:
# filter out not necessary excel file, only label files are needed
label_files = [f for f in xlsx_files if "labels" in f.name.lower()]
len(label_files)

16

In [5]:
label_files

[PosixPath('../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_Alle_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/ZEGA/ZEGA_52_ARC_eBKPh_260127_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/RALU/RALU_32_ARC_eBKPh_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/LUMU/LUMU_31_ARC_eBKPh_Alle_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/KEPR/KEPR_31_ARC_eBKPh_260209_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/KEHO/KEHO_31_ARC_eBKPh_260127_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/IMBU/IMBU_52_ARC_eBKPh_260127_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/GSRH/GSRH_31_ARC_eBKPh_Alle_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/GERB/250311_KGS/GERB_31_ARC_eBKPh_250221_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/GERB/241209_KGS/GERB_31_ARC_eBKPh_241209_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/ESAK/ESAK_21_ARC_eBKPh_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/CHLI/CHLI_51_ALE_Alle_eBKP-H_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/BRUT/BRUT_41_ARC_Alle_eBKPh_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/ADEM/260202_nach_Audit/ADEM_41_ARC_eBKPh_260202_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/ADEM/250617_KS/ADEM_41_ARC_eBKPh_250701_labels.xlsx'),
 PosixPath('../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM_41_ARC_eBKPh_250406_labels.xlsx')]

In [6]:
# process each ifc file and save data to .parquet
all_records = []
for excel_path in label_files:
    print(f"  Processing: {excel_path.name}")
    all_records.extend(extract_excel_label_informations(excel_path))

df = pd.DataFrame(all_records)
df

  Processing: ZUST_Alle_ARC_Alle_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: ZEGA_52_ARC_eBKPh_260127_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: RALU_32_ARC_eBKPh_labels.xlsx
  Processing: LUMU_31_ARC_eBKPh_Alle_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: KEPR_31_ARC_eBKPh_260209_labels.xlsx
  Processing: KEHO_31_ARC_eBKPh_260127_labels.xlsx
  Processing: IMBU_52_ARC_eBKPh_260127_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: GSRH_31_ARC_eBKPh_Alle_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: GERB_31_ARC_eBKPh_250221_labels.xlsx
  Processing: GERB_31_ARC_eBKPh_241209_labels.xlsx
  Processing: ESAK_21_ARC_eBKPh_labels.xlsx
  Processing: CHLI_51_ALE_Alle_eBKP-H_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: BRUT_41_ARC_Alle_eBKPh_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: ADEM_41_ARC_eBKPh_260202_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: ADEM_41_ARC_eBKPh_250701_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Processing: ADEM_41_ARC_eBKPh_250406_labels.xlsx

/Users/lukasstoeckli/GitLabProjects/hslu_baa_ebkph_classifier/.venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Modell,Geschoss,GKS Typ,IFC Entität,Predefined Type (Vordefinierter Typ),GUID,CHE_eBKP-H 2020 GKS,Farbe,excel_label_file_path,excel_label_name,Kurzname
0,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,1RK86fvnH4ahQHgYv2vVUR,"[D04 Technische Brandschutzanlage (A), D05 Wär...",NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,NaN
1,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3BD67pl1r2sAVv6QSpXopp,"[D04 Technische Brandschutzanlage (A), D05 Wär...",NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,NaN
2,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3bPK2j71bB1eOyKZIziNry,"[D04 Technische Brandschutzanlage (A), D05 Wär...",NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,NaN
3,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,04t05b7LbESvNTIP4YWVjz,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,NaN
4,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,1i$ZkNLnT42OfhsY2HRYEB,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels,NaN
...,...,...,...,...,...,...,...,...,...,...,...
120482,NaN,10. Dachgeschoss,NaN,IfcOpeningElement,RECESS,3zIqefldz0Q8QIicuLt7_Y,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM_41_ARC_eBKPh_250406
120483,NaN,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1PnmfCU5uVkG7pHP5Agbrr,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM_41_ARC_eBKPh_250406
120484,NaN,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1nshOve0Ay62mhSVNjs_My,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM_41_ARC_eBKPh_250406
120485,NaN,Dachaufsicht,"Allgemein, Unterkonstruktion Aussen",IfcRoof,FLAT_ROOF,3AYatVTD97uANw1KHHmGEN,"[F Bedachung Gebäude (A), F01 Dachhaut, F01.02...",NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM_41_ARC_eBKPh_250406
120486,NaN,Dachaufsicht,"Beton, Stahlbeton 240",IfcSlab,ROOF,3sSYhZnFnAJ9UPyQ0SMdp6,"[C04 Deckenkonstruktion, Dachkonstruktion, C04...",NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels,ADEM_41_ARC_eBKPh_250406

In [7]:
# merge Modell and Kurzname to one column
df["Modell"] = df["Modell"].fillna("") + " " + df["Kurzname"].fillna("")
df = df.drop(columns=["Kurzname"])
df

,Modell,Geschoss,GKS Typ,IFC Entität,Predefined Type (Vordefinierter Typ),GUID,CHE_eBKP-H 2020 GKS,Farbe,excel_label_file_path,excel_label_name
0,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,1RK86fvnH4ahQHgYv2vVUR,"[D04 Technische Brandschutzanlage (A), D05 Wär...",NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
1,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3BD67pl1r2sAVv6QSpXopp,"[D04 Technische Brandschutzanlage (A), D05 Wär...",NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
2,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3bPK2j71bB1eOyKZIziNry,"[D04 Technische Brandschutzanlage (A), D05 Wär...",NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
3,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,04t05b7LbESvNTIP4YWVjz,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
4,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,1i$ZkNLnT42OfhsY2HRYEB,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
...,...,...,...,...,...,...,...,...,...,...
120482,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,RECESS,3zIqefldz0Q8QIicuLt7_Y,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120483,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1PnmfCU5uVkG7pHP5Agbrr,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120484,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1nshOve0Ay62mhSVNjs_My,Nicht klassifiziert,NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120485,ADEM_41_ARC_eBKPh_250406,Dachaufsicht,"Allgemein, Unterkonstruktion Aussen",IfcRoof,FLAT_ROOF,3AYatVTD97uANw1KHHmGEN,"[F Bedachung Gebäude (A), F01 Dachhaut, F01.02...",NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120486,ADEM_41_ARC_eBKPh_250406,Dachaufsicht,"Beton, Stahlbeton 240",IfcSlab,ROOF,3sSYhZnFnAJ9UPyQ0SMdp6,"[C04 Deckenkonstruktion, Dachkonstruktion, C04...",NaN,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels

In [8]:
# remove column Modell
df = df.drop(columns=["Farbe"])
df

,Modell,Geschoss,GKS Typ,IFC Entität,Predefined Type (Vordefinierter Typ),GUID,CHE_eBKP-H 2020 GKS,excel_label_file_path,excel_label_name
0,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,1RK86fvnH4ahQHgYv2vVUR,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
1,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3BD67pl1r2sAVv6QSpXopp,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
2,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3bPK2j71bB1eOyKZIziNry,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
3,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,04t05b7LbESvNTIP4YWVjz,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
4,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,1i$ZkNLnT42OfhsY2HRYEB,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
...,...,...,...,...,...,...,...,...,...
120482,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,RECESS,3zIqefldz0Q8QIicuLt7_Y,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120483,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1PnmfCU5uVkG7pHP5Agbrr,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120484,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1nshOve0Ay62mhSVNjs_My,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120485,ADEM_41_ARC_eBKPh_250406,Dachaufsicht,"Allgemein, Unterkonstruktion Aussen",IfcRoof,FLAT_ROOF,3AYatVTD97uANw1KHHmGEN,"[F Bedachung Gebäude (A), F01 Dachhaut, F01.02...",../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120486,ADEM_41_ARC_eBKPh_250406,Dachaufsicht,"Beton, Stahlbeton 240",IfcSlab,ROOF,3sSYhZnFnAJ9UPyQ0SMdp6,"[C04 Deckenkonstruktion, Dachkonstruktion, C04...",../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels

In [9]:
# rename columns
df = df.rename(columns={
    "Modell": "model_name",
    "Geschoss": "storey",
    "GKS Typ": "type_gks",
    "IFC Entität": "ifc_entity",
    "Predefined Type (Vordefinierter Typ)": "predefined_type",
    "GUID": "guid",
    "CHE_eBKP-H 2020 GKS": "eBKPh"
})
df

,model_name,storey,type_gks,ifc_entity,predefined_type,guid,eBKPh,excel_label_file_path,excel_label_name
0,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,1RK86fvnH4ahQHgYv2vVUR,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
1,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3BD67pl1r2sAVv6QSpXopp,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
2,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3bPK2j71bB1eOyKZIziNry,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
3,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,04t05b7LbESvNTIP4YWVjz,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
4,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,1i$ZkNLnT42OfhsY2HRYEB,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
...,...,...,...,...,...,...,...,...,...
120482,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,RECESS,3zIqefldz0Q8QIicuLt7_Y,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120483,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1PnmfCU5uVkG7pHP5Agbrr,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120484,ADEM_41_ARC_eBKPh_250406,10. Dachgeschoss,NaN,IfcOpeningElement,NaN,1nshOve0Ay62mhSVNjs_My,Nicht klassifiziert,../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120485,ADEM_41_ARC_eBKPh_250406,Dachaufsicht,"Allgemein, Unterkonstruktion Aussen",IfcRoof,FLAT_ROOF,3AYatVTD97uANw1KHHmGEN,"[F Bedachung Gebäude (A), F01 Dachhaut, F01.02...",../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels
120486,ADEM_41_ARC_eBKPh_250406,Dachaufsicht,"Beton, Stahlbeton 240",IfcSlab,ROOF,3sSYhZnFnAJ9UPyQ0SMdp6,"[C04 Deckenkonstruktion, Dachkonstruktion, C04...",../../0_data/1_ifc_models/ADEM/250407_KGS/ADEM...,ADEM_41_ARC_eBKPh_250406_labels

In [10]:
# show project code distribution
df["model_name"].value_counts()

model_name
 CHLI_51_ALE_Haus B_eBKP-H    16179
 CHLI_51_ALE_Haus A_eBKP-H    12049
BRUT_41_ARC_Haus B_eBKPh       9673
 ADEM_41_ARC_eBKPh_260202      7331
 ADEM_41_ARC_eBKPh_250701      7331
 GSRH_31_ARC_eBKPh_V1          6989
 GSRH_31_ARC_eBKPh_V2          6769
 ZEGA_52_ARC_eBKPh_260127      6672
 ADEM_41_ARC_eBKPh_250406      6591
BRUT_41_ARC_Haus C_eBKPh       5235
BRUT_41_ARC_Haus A_eBKPh       4678
ZUST_B_ARC_EBK_                4138
ZUST_C_ARC_EBK_                4048
 LUMU_31_ARC_eBKPh_V3          3940
ZUST_A_ARC_EBK_                3855
 RALU_32_ARC_eBKPh             3149
 KEHO_31_ARC_eBKPh_260127      2556
 IMBU_52_ARC_eBKPh_260127      2099
 KEPR_31_ARC_eBKPh_260209      1370
 GERB_31_ARC_eBKPh_250221      1198
 GERB_31_ARC_eBKPh_241209      1132
 CHLI_51_ANG_Haus B             735
 CHLI_51_ANG_Haus A             576
 ESAK_21_ARC_eBKPh              549
ZUST_B_ARC_NGF_                 428
ZUST_C_ARC_NGF_                 428
ZUST_A_ARC_NGF_                 398
ZUST_P_ARC_EBK_                 176
 CHLI_51_AVM_Haus B              76
 CHLI_51_AVM_Haus A              48
ZUST_A_ARC_VOL_                  28
ZUST_C_ARC_VOL_                  26
ZUST_B_ARC_VOL_                  25
ZUST_ARC_NGF_                     6
ZUST_P_ARC_VOL_                   6
Name: count, dtype: int64

In [11]:
# save labels
df.to_parquet(OUTPUT_PATH, index=False)

print(f"\nSaved {len(df):,} rows to: {OUTPUT_PATH}\n")

Saved 120,487 rows to: label_data.parquet

In [12]:
# first data insight of columns
df.head(10)

,model_name,storey,type_gks,ifc_entity,predefined_type,guid,eBKPh,excel_label_file_path,excel_label_name
0,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,1RK86fvnH4ahQHgYv2vVUR,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
1,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3BD67pl1r2sAVv6QSpXopp,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
2,ZUST_ARC_NGF_,U01,NNF,IfcSpace,INTERNAL,3bPK2j71bB1eOyKZIziNry,"[D04 Technische Brandschutzanlage (A), D05 Wär...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
3,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,04t05b7LbESvNTIP4YWVjz,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
4,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,1i$ZkNLnT42OfhsY2HRYEB,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
5,ZUST_ARC_NGF_,EG0,Pyramide 27,IfcBuildingElementProxy,NOTDEFINED,1mvS9idiD3wBSng3jTXYT_,Nicht klassifiziert,../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
6,ZUST_A_ARC_EBK_,U02,AD B 8/25cm XPS 330,IfcWall,SOLIDWALL,0DLmVhL_15qxIJA0LgmJOE,"[C02 Wandkonstruktion, C02.01 Aussenwandkonstr...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
7,ZUST_A_ARC_EBK_,U02,AD B 8/25cm XPS 330,IfcWall,SOLIDWALL,0_Xw6h_cDEuuvuzC3obOEB,"[C02 Wandkonstruktion, C02.01 Aussenwandkonstr...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
8,ZUST_A_ARC_EBK_,U02,AD B 8/25cm XPS 330,IfcWall,SOLIDWALL,0rUUXrjYPCvgVQQgKa9xRV,"[C02 Wandkonstruktion, C02.01 Aussenwandkonstr...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels
9,ZUST_A_ARC_EBK_,U02,AD B 8/25cm XPS 330,IfcWall,SOLIDWALL,1g904JMoP6h8NXJ44EnEUb,"[C02 Wandkonstruktion, C02.01 Aussenwandkonstr...",../../0_data/1_ifc_models/ZUST/ZUST_Alle_ARC_A...,ZUST_Alle_ARC_Alle_labels

In [13]:
# show different entitties
len(df["ifc_entity"].value_counts()), len(df["predefined_type"].value_counts())

(40, 78)

In [14]:
# see all guid's, should be unique
df["guid"].value_counts()

guid
04t05b7LbESvNTIP4YWVjz    12
1i$ZkNLnT42OfhsY2HRYEB    12
1mvS9idiD3wBSng3jTXYT_    12
24lY8lXRzERO26ayPQs3PA     3
2CErjxDdn64B5GAL0Abp1I     3
                          ..
3F5awesTb1uRsC7pRJAH5h     1
3FrS$CC_rAhBBG2w6HwVeR     1
3yftf_2DjBs8is1$NUWV6g     1
3zIqefldz0Q8QIicuLt7_Y     1
3AYatVTD97uANw1KHHmGEN     1
Name: count, Length: 100613, dtype: int64

In [15]:
# show all dupliacate elements
counts = df["guid"].value_counts()
len(counts[counts > 1])

14860